### ISSUE TITLE
Win 7 - No visualizer magnifying glass and no visualizer assemblies created

### ISSUE THREAD

**Issue by abukres** [codingadventures/LINQBridgeVs#41] opened 2018-05-11 00:49 UTC
I am using Visual Studio 2017 15.7 and 1.4.5 of the extension. When I select "Bridge Solution', I don't get the confirmation message like the video is showing. No magnifying glass is showing and the visualizer assemblies don't get created after I rebuild the solution.

**Comment by codingadventures** [comment] 2018-05-11 09:42
hey thanks for reporting the issue. I haven't tried the extension with Visual Studio 2017 15.7, however from what you reported is very difficult to understand what went wrong. 

Please could you answer the following questions?
* which OS are you using?
* Was a previous version of LINQBridgeVs installed?
* has the LINQBridgeVS SETUP run the first time after you installed the extension?
<img src="https://raw.githubusercontent.com/codingadventures/LINQBridgeVs/master/Docs/VsRestart.PNG"/>
* could you please attach here the **ActivityLog.xml** of Visual Studio 2017? You can find it here: %APPDATA%\Microsoft\VisualStudio\15.0 (where 15.0 might be in the form of 15.0_c9a42992 or something similar) This log tells a lot if anything went wrong initializing the extension.

Thanks

**Comment by abukres** [comment] 2018-05-11 15:17
Yes I had an earlier version of it and I uninstalled it. I went through an install and reinstall it today. The ActivityLog.xml doesn't have any entries from today and there's no reference to LinqBridge. The setup didn't show up. I run VS in admin mode. The solution has ASP.NET and C# projects. I am using Windows 7.
I have another machine where it runs fine. The other machine runs Windows 10. Same VS version 15.7.
So the only difference I see is the Windows version.

**Comment by codingadventures** [comment] 2018-05-11 16:52
ok I think Windows 7 is not working with MahApps and the presentation framework. What it's puzzling me though is why it silently fails. I will spin up a virtual machine with Windows 7 to see what the issue is. One thing you can do on your end is to grab the sources and build the vsix using debug.

**Comment by codingadventures** [comment] 2018-10-07 22:02
fixed in the next release

**Closed by codingadventures** 2018-10-07 22:02 UTC
Labels: bug
